apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  generateName: seldon-s2i-run-
spec:
  workspaces:
  - name: workvol
    persistentVolumeClaim:
      claimName: workvol-pvc
  inputs:
    params:
      - name: PATH_CONTEXT
        value: "extraction"
      - name: TLSVERIFY
        value: "false"
      - name: BUILDER_IMAGE
        # NOTE: This should have been imported already, see create-tekton-cicd.sh
        # FIXME: project name should not be hard-coded
        value: image-registry.openshift-image-registry.svc:5000/fraud-demo-cicd/seldon-builder
      - name: BUILDER_IMAGE_SCRIPTS_DIR
        value: /s2i/bin/
      - name: IMAGE_TAG
        value: tr
      - name: LOGLEVEL
        value: '5'
      - name: MODEL_WRAPPER
        value: Wrapper
  outputs:
    resources:
      - name: image
        paths:
          - build-image/image
        resourceRef:
          name: model-image
  serviceAccountName: pipeline
  taskRef:
    kind: Task
    name: seldon-s2i
  timeout: 1h0m0s