apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  generateName: test-seldon-deploy-run-
spec:
  inputs:
    params:
      - name: MODEL_DEPLOY_URL
        value: 'http://gogs:3000/gogs/fraud_detection_support/raw/master/notebook/deploy/model_deployment.json'
      - name: PROJECT
        value: fraud-demo-dev
      - name: MODEL_IMAGE
        value: 'image-registry.openshift-image-registry.svc:5000/fraud-demo-dev/fraud-model:nvhwt'
  serviceAccountName: pipeline
  taskRef:
    kind: Task
    name: seldon-model-deploy