apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  generateName: train-model-run-
spec:
  workspaces:
    - name: workvol
      persistentVolumeClaim:
        claimName: workvol-pvc
  inputs:
    params:
      - name: MODEL_NAME
        value: "Train.py"
      - name: PATH_CONTEXT
        value: "extraction"
      - name: TRAIN_IMAGE
        value: image-registry.openshift-image-registry.svc:5000/fraud-demo-cicd/seldon-builder
  serviceAccountName: pipeline
  taskRef:
    kind: Task
    name: train-model