apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  generateName: test-sysdig-scan-run-
spec:
  workspaces:
    - name: workvol
      persistentVolumeClaim:
        claimName: workvol-pvc
  inputs:
    resources:
      - name: image
        resourceRef:
          name: model-image
        # resourceSpec:
        #   params:
        #     - name: url
        #   # NOTE: This file is pre-processed by the cicd installation script and replaces "demo-dev" with the proper
        #   # Demo Dev project name
        #       value: quay.io/mhildenb/homemade-serverless-java
        #  type: image
    params:
      - name: REPORT_CONTEXT
        value: scan-results
      - name: SYSDIG_SECRET_NAME
        value: sysdig-secret
      - name: IMAGE_TAG
        value: "2dxdp"
  serviceAccountName: pipeline
  taskRef:
    kind: Task
    name: sysdig-image-scan
  timeout: 1h0m0s