apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  generateName: test-seldon-deploy-run-
spec:
  workspaces:
    - name: workvol
      persistentVolumeClaim:
        claimName: workvol-pvc
  inputs:
    params:
      - name: MODEL_DEPLOY
        value: 'model_deployment.json'
      - name: PROJECT
        value: fraud-demo-dev
      - name: MODEL_IMAGE
        value: 'image-registry.openshift-image-registry.svc:5000/fraud-demo-dev/fraud-model:tr'
      - name: PATH_CONTEXT
        value: "extraction"
  serviceAccountName: pipeline
  taskRef:
    kind: Task
    name: seldon-model-deploy