apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: fraud-model-stage-pipeline-run-
spec:
  pipelineRef:
    name: fraud-model-stage-pipeline
  params:
    - name: PAYLOAD
      value: |
        {
          \"BUILD_NUM\": \"q6l6b\",
          \"MODEL_DEPLOYMENT_URL\": \"http://gogs-fraud-demo-cicd.apps.demo45.openshifttc.com/gogs/fraud_detection_stage/raw/6f3874cbd8834ea94609abd3b622e803fbe312b1/notebook/deploy/model_deployment.json\"
        }
  resources:
  - name: app-image
    resourceRef:
      name: model-image
  timeout: 1h0m0s
    