apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: fraud-model-dev-pipeline-run-
spec:
  pipelineRef:
    name: fraud-model-dev-pipeline
  params:
  # uncomment these parameters if you want to point to the internal git repo, pointing external might
  # make iteration easier
  - name: GIT_REPO
    value: "http://gogs:3000/gogs/fraud_detection_support.git"
#    value: "https://github.com/hatmarch/fraud_detection_support.git"
  - name: PATH_CONTEXT
    value: "notebook"
  - name: NOTEBOOK_NAME
    value: "frauddetection.ipynb"
  resources:
  - name: app-image
    resourceRef:
      name: model-image
  workspaces:
  - name: local-workspace
    persistentVolumeClaim:
      claimName: workvol-pvc
  timeout: 1h0m0s
    