apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: seldon-model-deploy
spec:
  params:
    - name: MODEL_DEPLOY_URL
      type: string 
      description: The URL of the model that is to be deployed.  This usually refers into the raw code of a git repo
    - name: PROJECT
      type: string
      description: The name of the project to deploy the model into
    - name: MODEL_IMAGE
      type: string
      description: The name of the model image that should be deployed
  steps:
    - name: run-commands
      image: quay.io/openshift/origin-cli:latest
      script: |
        #!/usr/bin/env bash
        set -e -o pipefail

        # First find the deployment file
        MODEL_DEPLOY_FILE=/tmp/seldon_deploy.json
        HTTP_RESULT=$(curl -sL -w "%{http_code}" $(params.MODEL_DEPLOY_URL) -o ${MODEL_DEPLOY_FILE})
        if [[ ${HTTP_RESULT} != 200 ]]; then
          echo "Could not find model deployment template at $(params.MODEL_DEPLOY_URL).  HTTP result code was ${HTTP_RESULT}"
          exit 1
        fi

        # replace the token in the MODEL_DEPLOY with the MODEL_IMAGE
        REPL_MODEL_DEPLOY_PATH="/tmp/seldon_deploy_replaced.json"
        
        cat ${MODEL_DEPLOY_FILE} | sed 's#\${SELDON_IMAGE_REPLACE}#$(params.MODEL_IMAGE)#g' > ${REPL_MODEL_DEPLOY_PATH}
        echo "Deployment is: "
        cat ${REPL_MODEL_DEPLOY_PATH}

        TARGET_PROJECT=$(params.PROJECT)
        # actually apply the deployment
        # Get the name of the deployment as output from the oc application
        SELDON_DEPLOY_NAME=$(oc apply -f ${REPL_MODEL_DEPLOY_PATH} -o jsonpath='{.metadata.name}' -n ${TARGET_PROJECT}) 
        echo "Waiting for $SELDON_DEPLOY_NAME to appear."
        while [[ -z "$(oc get deployment -l seldon-deployment-id="${SELDON_DEPLOY_NAME}" -n ${TARGET_PROJECT} 2>/dev/null)" ]]; do
          echo -n "."
          sleep 1
        done
        DEPLOYMENT=$(oc get deployment -l seldon-deployment-id="${SELDON_DEPLOY_NAME}" -n ${TARGET_PROJECT} -o jsonpath='{.items[0].metadata.name}')

        echo "Waiting for deployment ${DEPLOYMENT} to complete"
        oc rollout status deployment/${DEPLOYMENT} -n ${TARGET_PROJECT}
