---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: model-trigger-template
spec:
  params:
  - name: gitrevision
    description: The git revision
    default: master
  - name: gitrepositoryurl
    description: The git repository url
  - name: message
    description: The message to print
    default: This is the default message
  - name: contenttype
    description: The Content-Type of the event
  resourcetemplates:
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineRun
    metadata:
      generateName: fraud-model-dev-pipeline-triggered-run-
      labels:
        tekton.dev/pipeline: fraud-model-dev-pipeline
    spec:
      pipelineRef:
        name: fraud-model-dev-pipeline
      params:
      - name: GIT_REPO
        value: $(params.gitrepositoryurl)
      - name: GIT_REVISION
        value: $(params.gitrevision)
      - name: GIT_MESSAGE
        value: $(params.message)
      resources:
      - name: app-image
        resourceRef:
          name: model-image
      workspaces:
      - name: local-source
        persistentVolumeClaim:
          claimName: source-pvc