# apiVersion: v1
# kind: Namespace
# metadata:
# #  labels:
#   name: seldon-core
# ---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: seldon-operator
  namespace: openshift-operators
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: seldon-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: seldon-operator.v1.2.2
  #startingCSV: seldon-operator.v1.1.0