apiVersion: constraints.gatekeeper.sh/v1beta1
kind: AIModelAccuracyThreshold
metadata:
  name: model-accuracy-threshold
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: ["ai.devops.demo"]
        kinds: ["ModelAccuracy"]
    namespaces:
      - "demo-cicd"
  parameters:
    accuracyThreshold: 0.93