---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: slack-trigger-template
spec:
  params:
  - name: payload
    description: The payload from the slack prompting
    default: "unknown"
  resourcetemplates:
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineRun
    metadata:
      generateName: fraud-model-stage-pipeline-triggered-run-
      labels:
        tekton.dev/pipeline: fraud-model-stage-pipeline
    spec:
      pipelineRef:
        name: fraud-model-stage-pipeline
      params:
      - name: PAYLOAD
        value: $(params.payload)
      resources:
      - name: app-image
        resourceRef:
          name: model-image