apiVersion: tekton.dev/v1alpha1
kind: Condition
metadata:
  name: secret-exists
spec:
  params:
    - name: SECRET_NAME
      description: "The name of the secret to check for in the specified project"
    - name: PROJECT
      description: "The name of the project in which to seek SECRET_NAME.  Defaults to the project this condition is defined in"
      default: ""
  check:
    image: quay.io/openshift/origin-cli:latest
    script: |
        #!/usr/bin/env bash
        set -e -o pipefail

        declare CHECK_PRJ="$(params.PROJECT)"
        if [[ -z "${CHECK_PRJ}" ]]; then
            echo "Looking to the pod to determine the current namespace"
            CHECK_PRJ=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
        fi

        echo "command to run is: oc get secret $(params.SECRET_NAME) -n ${CHECK_PRJ} 2>/dev/null"

        # check for non-empty string result looking for secret
        test -n "$(oc get secret $(params.SECRET_NAME) -n ${CHECK_PRJ} 2>/dev/null)"