kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: name
  namespace: namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
  volumeName: volumeName
  volumeMode: Filesystem
